// <auto-generated />
namespace EthnicStyles.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview1-19506-01")]
    public sealed partial class ET_20192 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ET_20192));
        
        string IMigrationMetadata.Id
        {
            get { return "201910260236483_ET_20192"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
